"""In-app Feature Inspector / arsenal playbook.

Human-readable explanations, use-cases, expected outputs, and legal notes.
This is documentation served to the UI — not an execution surface.
"""

from __future__ import annotations

from typing import Any, Optional

ENTRIES: list[dict[str, Any]] = [
    {
        "id": "apex",
        "name": "Apex Master Mode",
        "category": "orchestration",
        "summary": "One prompt → planner tree → public-source dossier with citations, confidence, and a relationship graph.",
        "use_when": "You have a company, domain, or 'Company X and its C-suite' style question and want a cited pack, not a scrape dump.",
        "expected": "Headline, executive summary, key findings with citation ids, gaps, Person→Company→Domain graph.",
        "legal": "Public registries, RSS, archives, and documented APIs only. Live Active Probe is never started from Apex.",
        "outputs": ["dossier", "citations", "knowledge graph"],
    },
    {
        "id": "research_discovery",
        "name": "Discovery Inbox (Layer A)",
        "category": "orchestration",
        "summary": "Collects public traces, registry hits, and archive notes into an unverified inbox. Snippets are traces, not read sources.",
        "use_when": "You want coverage first without pretending every hit is true.",
        "expected": "Research Inbox with documents, candidate entities, claims at not_requested. Banner that a source ≠ a true claim.",
        "legal": "Same access policy, SSRF, privacy layer, and risk gate as the rest of ArgosScout. No probe, no CAPTCHA bypass. Academic hits are bibliographic traces.",
        "outputs": ["documents", "claims", "entity_candidates", "coverage_map"],
    },
    {
        "id": "research_verification",
        "name": "Verification Center (Layer B)",
        "category": "orchestration",
        "summary": "Optional second pass: analyze collected evidence or cross-check with a separate budget. No single truth score.",
        "use_when": "You picked claims/entities to assess. Do not run it silently after every search.",
        "expected": "Per-claim statuses (supported/disputed/contradicted/insufficient_evidence) plus reliability, quality, freshness, use-risk, independence.",
        "legal": "Assessments never overwrite source excerpts. Human merge/split is logged. Erase removes derived records too.",
        "outputs": ["assessments", "evidence_links", "gap_map"],
    },
    {
        "id": "research_graph",
        "name": "Evidence Graph",
        "category": "orchestration",
        "summary": "Interactive relationship graph: Target, Organization, Person, Domain/Host, registry identifiers, and public artifacts. Layer A dashed amber, Layer B solid emerald, disputed dotted red.",
        "use_when": "You need to see how traces connect, then inspect one edge's sources.",
        "expected": "SVG graph with an inspector drawer. Verify Only This Edge runs Layer B analyze on that relation.",
        "legal": "Same dual-layer rules. Graph edges are hypotheses until Layer B says otherwise. Unverified banner still applies.",
        "outputs": ["nodes", "edges", "inspector"],
    },
    {
        "id": "research_dossier",
        "name": "Forensic executive dossier",
        "category": "export",
        "summary": "Export JSON, Markdown, or print-ready HTML with classification, NIST/OSINT discipline map, SHA-256 hash manifest, case timeline, Layer B table, Layer A annex disclaimer, and chain-of-custody checksums.",
        "use_when": "A C-level or legal reader needs a file, not a dashboard.",
        "expected": "Header with UTC + session hash, case.hash_manifest, timeline of research events, executive summary, annex disclaimer.",
        "legal": "INTERNAL USE / OSINT COMPLIANT. Annex items are traces, not facts. Secrets redacted.",
        "outputs": ["json", "markdown", "html", "hash_manifest", "timeline"],
    },
    {
        "id": "research_snapshots",
        "name": "Research snapshots & Wayback diff",
        "category": "orchestration",
        "summary": "Immutable ResearchSnapshot hashes plus Compare Snapshots (added/removed/modified). First-run lookback uses Internet Archive CDX.",
        "use_when": "You care what changed, not only the current scrape.",
        "expected": "Two-run diff of entities, domains, and claims; or a Wayback size/date lookback without a prior local run.",
        "legal": "Archive.org CDX is public. Lookback does not rewrite live pages or bypass paywalls.",
        "outputs": ["snapshots", "diff", "lookback"],
    },
    {
        "id": "pheromone_telemetry",
        "name": "Pheromone efficiency telemetry",
        "category": "probe",
        "summary": "Mapped routes, skipped HTTP calls, and a cost-efficiency index versus re-crawling dead ends. Inspect map or flush cache explicitly.",
        "use_when": "You want to see what memory saved, or force a fresh probe of a host.",
        "expected": "Telemetry cards plus a route list. Flush requires confirm=true and keeps historical counters.",
        "legal": "Flush is operator-initiated. Poison routes skip later crawls; they do not attack the host.",
        "outputs": ["telemetry", "pheromone_map"],
    },
    {
        "id": "quick_scrape",
        "name": "Quick Scrape",
        "category": "extract",
        "summary": "Single-page HTTP extract of title, text, links, and meta via Cruel + BeautifulSoup.",
        "use_when": "You already have a public URL and need the visible text fast.",
        "expected": "Extracted fields plus a short text preview.",
        "legal": "SSRF-guarded public http(s) only. Respect robots and privacy layer. Do not point at hosts you may not fetch.",
        "outputs": ["title", "text", "links", "meta"],
    },
    {
        "id": "universal",
        "name": "Universal Scrape",
        "category": "extract",
        "summary": "Scraper.io fallback ladder: RSS → HTTP → optional browser → aggressive HTML.",
        "use_when": "Blogs, feeds, or multi-article sources.",
        "expected": "A list of items (title, url, content) from the first strategy that works.",
        "legal": "Same as Quick Scrape. Browser tier is identity-consistent UA/viewport, not a challenge bypass.",
        "outputs": ["items", "strategy"],
    },
    {
        "id": "detective",
        "name": "Smart Detective",
        "category": "intelligence",
        "summary": "Layer-aware pipeline: API Echo → SEO Autopsy → Common Crawl → Wayback → semantic extract, then lawful fallback if live DOM fails.",
        "use_when": "A site may block scrapers, or you want structured data the page already publishes.",
        "expected": "winning_method, findings per stage, GDPR summary.",
        "legal": "Follows the selected privacy layer. Ghost stays on archives. No login-wall bypass.",
        "outputs": ["winning_method", "findings", "gdpr"],
    },
    {
        "id": "lawful_fallback",
        "name": "Lawful fallback tree",
        "category": "intelligence",
        "summary": "When live DOM is blocked: RSS/Atom, sitemap/JSON-LD, CDN hosts, RDAP, DNS TXT, Wayback, Common Crawl.",
        "use_when": "403/captcha/empty page — you still need public evidence.",
        "expected": "winning_method plus per-method findings.",
        "legal": "Passive public sources first. FlareSolverr / TLS impersonate run only after the operator risk gate.",
        "outputs": ["rss", "rdap", "wayback", "common_crawl"],
    },
    {
        "id": "swarm",
        "name": "Swarm Pheromones",
        "category": "probe",
        "summary": "Parallel micro-fetchers that remember sweet (useful) and poison (blocked) URL patterns in Redis or SQLite.",
        "use_when": "Authorized mapping of a site you operate, so later jobs skip dead ends.",
        "expected": "Per-worker notes and a pheromone log.",
        "legal": "Part of Active Probe. Live runs require authorized_target=true. Default is dry_run.",
        "outputs": ["pheromones", "worker results"],
    },
    {
        "id": "provocative_stock",
        "name": "Provocative Stock",
        "category": "probe",
        "summary": "On a shop you are allowed to test, submit an extreme cart quantity to read stock/validation errors the UI already returns.",
        "use_when": "You own the storefront and need availability signals that the product page hides.",
        "expected": "Request/response notes in dry_run; live only with authorization.",
        "legal": "Authorized testing only. Not for inventory theft against third parties. Prefer dry_run.",
        "outputs": ["validation_errors", "hints"],
    },
    {
        "id": "api_fuzz",
        "name": "API Fuzz",
        "category": "probe",
        "summary": "Shadow-map of same-origin paths the HTML already references, plus conservative path guesses.",
        "use_when": "Documenting your own app's public API surface.",
        "expected": "Candidate URLs and status codes. Not an exploit framework.",
        "legal": "No payload exploits, no auth bypass. Live requires authorized_target=true.",
        "outputs": ["candidates", "statuses"],
    },
    {
        "id": "temporal",
        "name": "Temporal Spoofing",
        "category": "probe",
        "summary": "Shift the browser clock for pages that gate content on Date() (countdown, embargo).",
        "use_when": "Authorized review of time-gated UX on a property you control.",
        "expected": "Before/after notes of visible content.",
        "legal": "Does not forge server-side sessions or TLS. Authorized hosts only.",
        "outputs": ["visible_delta"],
    },
    {
        "id": "ghost_cursor",
        "name": "Ghost Cursor",
        "category": "browser",
        "summary": "Bezier mouse paths, variable typing cadence, scroll pauses, and tiny viewport nudges during authorized Playwright sessions.",
        "use_when": "Vision scrape on a site that expects a real viewport — not to defeat bot management.",
        "expected": "More complete screenshots on ordinary pages.",
        "legal": "Human-like cadence. Canvas/WebGL profile overrides require the fingerprint_profiles risk option.",
        "outputs": ["screenshot"],
    },
    {
        "id": "privacy_layers",
        "name": "Privacy Layers",
        "category": "compliance",
        "summary": "ghost / standard / eu_shield / de_fortress / hunter — which methods are allowed and how PII is gated.",
        "use_when": "Research that must stay GDPR-aware or archive-only.",
        "expected": "Policy profile, allowed methods, GDPR mask counts.",
        "legal": "de_fortress and eu_shield tighten live collection and mask personal emails. Hunter is for ROW authorized research.",
        "outputs": ["layer", "allowed_methods"],
    },
    {
        "id": "corporate",
        "name": "Corporate intelligence",
        "category": "osint",
        "summary": "SEC EDGAR search, Companies House (API or search URL), OpenCorporates, GitHub public org metadata, careers-page signals, HTML tech-stack.",
        "use_when": "Company due diligence from public registries.",
        "expected": "Filings/search URLs, stack signatures, hiring page hits.",
        "legal": "Public APIs and search URLs. GitHub commit emails require the operator risk option.",
        "outputs": ["registries", "stack", "hiring"],
    },
    {
        "id": "people",
        "name": "People footprint",
        "category": "osint",
        "summary": "Wikipedia summary, GitHub public user, news search, LinkedIn search URL.",
        "use_when": "Public professional context for a named person already in the news or Wikipedia.",
        "expected": "Public snippets and search links — not a dossier of private emails.",
        "legal": "LinkedIn scrape and GitHub commit-email harvest stay off until the operator reads the notice, types the phrase, and enables those options. No stalking of private individuals.",
        "outputs": ["wikipedia", "github", "news", "linkedin_search"],
    },
    {
        "id": "byok",
        "name": "BYOK LLM hub",
        "category": "system",
        "summary": "Bring OpenRouter, OpenAI, Anthropic, Groq, NVIDIA, Hugging Face, or local Ollama. Light tasks go to fast/cheap models; dossiers use reasoning models.",
        "use_when": "You want Claude/DeepSeek/Llama without locking to NVIDIA/Groq.",
        "expected": "Health routing shows light vs reasoning provider:model chains.",
        "legal": "Keys stay on your host. Never paste secrets into Copilot chat.",
        "outputs": ["routing.light", "routing.reasoning"],
    },
    {
        "id": "academic",
        "name": "Academic bibliographic pass",
        "category": "osint",
        "summary": "OpenAlex, Crossref, and arXiv public search. Papers land in Layer A as traces — a DOI landing page is not a read full text.",
        "use_when": "Coverage is thin on scholarly sources, or the Academic desk is selected.",
        "expected": "Documents with source_type=academic, venue/year metadata, unverified banner.",
        "legal": "Public bibliographic APIs only. No paywall bypass.",
        "outputs": ["title", "url", "venue", "year"],
    },
    {
        "id": "reflection",
        "name": "Post-discovery reflection",
        "category": "orchestration",
        "summary": "After Discovery, a local heuristic records coverage gaps (academic, second origin, registry URL-only, unverified). Gaps become mission chips. No extra LLM.",
        "use_when": "You want the next cheap pass without inventing a truth score.",
        "expected": "coverage.reflection.gaps plus 2–4 chips. Copilot cannot confirm chip spend.",
        "legal": "Reflection does not start Layer B or live probe.",
        "outputs": ["gaps", "mission_chips"],
    },
    {
        "id": "case_discipline",
        "name": "NIST / OSINT case discipline",
        "category": "export",
        "summary": "Inspector maps collection → examination → analysis → reporting onto Layers A/B, origin_group, and the portable case file.",
        "use_when": "You need to explain the method, not only the findings.",
        "expected": "case.discipline plus hash_manifest and timeline in JSON export.",
        "legal": "Methodology notes only. Not a certification that the operator followed NIST.",
        "outputs": ["discipline", "hash_manifest", "timeline"],
    },
    {
        "id": "steering",
        "name": "Human-in-the-loop steering",
        "category": "orchestration",
        "summary": "Pause, resume, skip a desk, add an academic/registry/archive loop, or set the Copilot desk on an existing task. Loops stay Layer A.",
        "use_when": "Discovery finished but you want another collector without starting verification.",
        "expected": "Task status paused/done, extra traces, same unverified banner.",
        "legal": "Steering never confirms mission-chip spend and never launches Active Probe.",
        "outputs": ["steering", "inbox"],
    },
    {
        "id": "operator_ingest",
        "name": "Operator file ingest",
        "category": "orchestration",
        "summary": "Paste text/markdown/csv/json/html into Layer A as source_type=operator_upload with a SHA-256 of the body.",
        "use_when": "You already hold a filing, note, or excerpt and want it in the same inbox.",
        "expected": "Unverified document. Presence is not factuality. Verification is not started.",
        "legal": "You are responsible for the lawful basis of anything you upload.",
        "outputs": ["document", "sha256"],
    },
    {
        "id": "copilot_desks",
        "name": "Copilot desks",
        "category": "system",
        "summary": "Synthesist, Registry, Academic, and DPO prompt deltas. Same tools, same risk gate, no extra rights.",
        "use_when": "You want routing bias without a new permission surface.",
        "expected": "Rule/LLM plans prefer that desk's tools. DPO never enables high-risk switches.",
        "legal": "A desk is not a capability grant. High-risk LinkedIn/GitHub/live probe still need the operator notice, proxy, and explicit consent.",
        "outputs": ["desk", "prefer"],
    },
    {
        "id": "risk_gate",
        "name": "Operator risk gate",
        "category": "compliance",
        "summary": "Notice v2: high-risk options stay off until you read the notice, confirm authorized use, type I ACCEPT THE RISK, set YOUR HTTP/SOCKS proxy, and enable each switch.",
        "use_when": "You have a lawful basis and need FlareSolverr, TLS impersonation, fingerprint profiles, LinkedIn public fetch, GitHub commit emails, or authorized surface enumeration.",
        "expected": "Per-capability flags in Settings. Proxy-required options refuse without proxy_url. APIs return 403 until the matching flag is on.",
        "legal": "You accept all liability. Proxy is yours. These options can violate site terms or GDPR if misused. Revoke anytime. No exploits, stealth login, or credential stuffing.",
        "outputs": ["acknowledged", "capabilities", "proxy_configured"],
    },
    {
        "id": "flaresolverr",
        "name": "FlareSolverr (BYO)",
        "category": "high-risk",
        "summary": "Forwards a URL to YOUR FlareSolverr instance. ArgosScout does not include a Cloudflare solver.",
        "use_when": "You run FlareSolverr locally and are allowed to fetch the target.",
        "expected": "HTML from the sidecar, or an error if the instance is down.",
        "legal": "Authorized hosts only. Enabling this does not grant extra rights against third-party sites.",
        "outputs": ["html_preview", "status"],
    },
    {
        "id": "tls_impersonate",
        "name": "TLS/JA3 impersonation",
        "category": "high-risk",
        "summary": "Optional curl_cffi Chrome TLS profile for GET via YOUR HTTP/SOCKS proxy. pip install curl_cffi.",
        "use_when": "Authorized testing against TLS fingerprint blocks, with your egress proxy in place.",
        "expected": "Status and HTML preview via impersonated client through the operator proxy.",
        "legal": "Not a WAF exploit. Still SSRF-gated. Requires proxy_url. Authorized use only.",
        "outputs": ["status", "impersonate"],
    },
    {
        "id": "fingerprint_profiles",
        "name": "Canvas / WebGL / Audio profiles",
        "category": "high-risk",
        "summary": "Playwright init script aligns platform, WebGL vendor/renderer, and AudioContext with the UA. No canvas noise.",
        "use_when": "Vision scrape on a property you may browse that inspects navigator/WebGL.",
        "expected": "Same screenshot pipeline with a coherent profile applied.",
        "legal": "Not a full anti-detect kit and not a challenge solver.",
        "outputs": ["init_script"],
    },
    {
        "id": "linkedin_fetch",
        "name": "LinkedIn public fetch",
        "category": "high-risk",
        "summary": "Unauthenticated GET of a LinkedIn URL through YOUR proxy. Login walls and 999 stop the attempt.",
        "use_when": "You have a lawful basis, a proxy you operate, and only need public HTML/JSON-LD.",
        "expected": "Title and JSON-LD if the page is actually public; otherwise blocked.",
        "legal": "LinkedIn terms generally prohibit scraping. No session, no stealth login. Requires proxy_url.",
        "outputs": ["title", "json_ld_preview"],
    },
    {
        "id": "github_commit_emails",
        "name": "GitHub commit author emails",
        "category": "high-risk",
        "summary": "Reads author.email from the public commits API for a repo you name, via YOUR proxy.",
        "use_when": "Due diligence on a public repository you specify — not a person-hunt across GitHub.",
        "expected": "Deduped name/email pairs, including noreply.github.com addresses.",
        "legal": "Personal data. GDPR still applies. Requires proxy_url. Do not build marketing or stalking lists.",
        "outputs": ["authors"],
    },
    {
        "id": "authorized_surface_enum",
        "name": "Authorized HTTP surface enumeration",
        "category": "high-risk",
        "summary": "Live Active Probe / same-origin path mapping on a host you confirm you may test. Requires proxy AND authorized_target. Dry-run stays available without this flag.",
        "use_when": "You own or are contracted to test the host and need public /api path discovery.",
        "expected": "Probe modes on that host through your proxy. No exploit payloads.",
        "legal": "No auth bypass, no ransomware tooling, no fuzz payloads. Copilot cannot enable this switch.",
        "outputs": ["probe_results"],
    },
    {
        "id": "argos_conduit",
        "name": "Argos Conduit",
        "category": "high-risk",
        "summary": "In-app loopback HTTP/CONNECT proxy. Policy (SSRF) + Witness Ledger. Optional upstream: your proxy or a Tor SOCKS port you already run.",
        "use_when": "You want the product to own egress policy without shipping a public stealth network.",
        "expected": "listen http://127.0.0.1:<port>, hash-chained hops, loopback_only=true.",
        "legal": "Never binds a public interface. Does not launch Tor. No residential rotation. You accept liability for upstream use.",
        "outputs": ["listen", "witness"],
    },
    {
        "id": "argos_veil",
        "name": "Argos Veil (witnessed quiet)",
        "category": "high-risk",
        "summary": "Split-horizon quiet mode: Lantern (OpenAlex/Crossref/arXiv/archives) stays identified; live third-party fetches jitter, drop extra headers, and write the Witness Ledger.",
        "use_when": "You need anti-correlation and an audit trail, not invisibility.",
        "expected": "lane=lantern|veil hops. Not deniable. No stealth login, no canvas noise.",
        "legal": "Requires proxy or Conduit plus the operator notice. Copilot cannot enable Veil.",
        "outputs": ["lane", "hop_hash"],
    },
    {
        "id": "mcp_sse",
        "name": "Research MCP + SSE",
        "category": "system",
        "summary": "JSON-RPC tools/list and tools/call at POST /mcp, plus GET /api/v1/research/{id}/stream for live events.",
        "use_when": "An external operator agent should drive Discovery without sitting in the UI.",
        "expected": "Same tools and confirmation rules as Copilot. Chip spend stays unconfirmed via MCP.",
        "legal": "API key required. High-risk LinkedIn/GitHub/probe tools are not on the MCP surface.",
        "outputs": ["tools", "sse_events"],
    },
]


def get_playbook() -> dict[str, Any]:
    return {
        "title": "ArgosScout Feature Inspector",
        "stance": (
            "ArgosScout is a privacy-first research OS. Discovery collects unverified traces; "
            "Verification is an optional second pass and never a silent truth score. "
            "High-risk options stay off until the operator reads the notice, types the acceptance phrase, "
            "and sets BYO proxy or Argos Conduit for egress. Argos Veil is witnessed quiet (lantern/veil split), "
            "not stealth login. MCP/SSE use the same gates. "
            "ArgosScout does not ship exploits, stealth logins, or credential stuffing. "
            "When a live page refuses inspection, prefer the lawful fallback tree."
        ),
        "entries": ENTRIES,
        "ids": [e["id"] for e in ENTRIES],
    }


def get_entry(entry_id: str) -> Optional[dict[str, Any]]:
    for item in ENTRIES:
        if item["id"] == entry_id:
            return item
    return None
