"""In-app Feature Inspector / arsenal playbook.

Human-readable explanations, use-cases, expected outputs, and legal notes.
This is documentation served to the UI — not an execution surface.
"""

from __future__ import annotations

from typing import Any, Optional

ENTRIES: list[dict[str, Any]] = [
    {
        "id": "apex",
        "name": "Apex Master Mode",
        "category": "orchestration",
        "summary": "One prompt → planner tree → public-source dossier with citations, confidence, and a relationship graph.",
        "use_when": "You have a company, domain, or 'Company X and its C-suite' style question and want a cited pack, not a scrape dump.",
        "expected": "Headline, executive summary, key findings with citation ids, gaps, Person→Company→Domain graph.",
        "legal": "Public registries, RSS, archives, and documented APIs only. Live Active Probe is never started from Apex.",
        "outputs": ["dossier", "citations", "knowledge graph"],
    },
    {
        "id": "research_discovery",
        "name": "Discovery Inbox (Layer A)",
        "category": "orchestration",
        "summary": "Collects public traces, registry hits, and archive notes into an unverified inbox. Snippets are traces, not read sources.",
        "use_when": "You want coverage first without pretending every hit is true.",
        "expected": "Research Inbox with documents, candidate entities, claims at not_requested. Banner that a source ≠ a true claim.",
        "legal": "Same access policy, SSRF, privacy layer, and risk gate as the rest of ArgosScout. No probe, no CAPTCHA bypass.",
        "outputs": ["documents", "claims", "entity_candidates", "coverage_map"],
    },
    {
        "id": "research_verification",
        "name": "Verification Center (Layer B)",
        "category": "orchestration",
        "summary": "Optional second pass: analyze collected evidence or cross-check with a separate budget. No single truth score.",
        "use_when": "You picked claims/entities to assess. Do not run it silently after every search.",
        "expected": "Per-claim statuses (supported/disputed/contradicted/insufficient_evidence) plus reliability, quality, freshness, use-risk, independence.",
        "legal": "Assessments never overwrite source excerpts. Human merge/split is logged. Erase removes derived records too.",
        "outputs": ["assessments", "evidence_links", "gap_map"],
    },
    {
        "id": "research_graph",
        "name": "Evidence Graph",
        "category": "orchestration",
        "summary": "Interactive relationship graph: Target, Organization, Person, Domain/Host, registry identifiers, and public artifacts. Layer A dashed amber, Layer B solid emerald, disputed dotted red.",
        "use_when": "You need to see how traces connect, then inspect one edge's sources.",
        "expected": "SVG graph with an inspector drawer. Verify Only This Edge runs Layer B analyze on that relation.",
        "legal": "Same dual-layer rules. Graph edges are hypotheses until Layer B says otherwise. Unverified banner still applies.",
        "outputs": ["nodes", "edges", "inspector"],
    },
    {
        "id": "research_dossier",
        "name": "Forensic executive dossier",
        "category": "export",
        "summary": "Export JSON, Markdown, or print-ready HTML with classification, risk bar, Layer B table, Layer A annex disclaimer, and chain-of-custody checksums.",
        "use_when": "A C-level or legal reader needs a file, not a dashboard.",
        "expected": "Header with UTC + session hash, executive summary (heuristic unless BYOK LLM is allowed), annex disclaimer.",
        "legal": "INTERNAL USE / OSINT COMPLIANT. Annex items are traces, not facts. Secrets redacted.",
        "outputs": ["json", "markdown", "html"],
    },
    {
        "id": "research_snapshots",
        "name": "Research snapshots & Wayback diff",
        "category": "orchestration",
        "summary": "Immutable ResearchSnapshot hashes plus Compare Snapshots (added/removed/modified). First-run lookback uses Internet Archive CDX.",
        "use_when": "You care what changed, not only the current scrape.",
        "expected": "Two-run diff of entities, domains, and claims; or a Wayback size/date lookback without a prior local run.",
        "legal": "Archive.org CDX is public. Lookback does not rewrite live pages or bypass paywalls.",
        "outputs": ["snapshots", "diff", "lookback"],
    },
    {
        "id": "pheromone_telemetry",
        "name": "Pheromone efficiency telemetry",
        "category": "probe",
        "summary": "Mapped routes, skipped HTTP calls, and a cost-efficiency index versus re-crawling dead ends. Inspect map or flush cache explicitly.",
        "use_when": "You want to see what memory saved, or force a fresh probe of a host.",
        "expected": "Telemetry cards plus a route list. Flush requires confirm=true and keeps historical counters.",
        "legal": "Flush is operator-initiated. Poison routes skip later crawls; they do not attack the host.",
        "outputs": ["telemetry", "pheromone_map"],
    },
    {
        "id": "quick_scrape",
        "name": "Quick Scrape",
        "category": "extract",
        "summary": "Single-page HTTP extract of title, text, links, and meta via Cruel + BeautifulSoup.",
        "use_when": "You already have a public URL and need the visible text fast.",
        "expected": "Extracted fields plus a short text preview.",
        "legal": "SSRF-guarded public http(s) only. Respect robots and privacy layer. Do not point at hosts you may not fetch.",
        "outputs": ["title", "text", "links", "meta"],
    },
    {
        "id": "universal",
        "name": "Universal Scrape",
        "category": "extract",
        "summary": "Scraper.io fallback ladder: RSS → HTTP → optional browser → aggressive HTML.",
        "use_when": "Blogs, feeds, or multi-article sources.",
        "expected": "A list of items (title, url, content) from the first strategy that works.",
        "legal": "Same as Quick Scrape. Browser tier is identity-consistent UA/viewport, not a challenge bypass.",
        "outputs": ["items", "strategy"],
    },
    {
        "id": "detective",
        "name": "Smart Detective",
        "category": "intelligence",
        "summary": "Layer-aware pipeline: API Echo → SEO Autopsy → Common Crawl → Wayback → semantic extract, then lawful fallback if live DOM fails.",
        "use_when": "A site may block scrapers, or you want structured data the page already publishes.",
        "expected": "winning_method, findings per stage, GDPR summary.",
        "legal": "Follows the selected privacy layer. Ghost stays on archives. No login-wall bypass.",
        "outputs": ["winning_method", "findings", "gdpr"],
    },
    {
        "id": "lawful_fallback",
        "name": "Lawful fallback tree",
        "category": "intelligence",
        "summary": "When live DOM is blocked: RSS/Atom, sitemap/JSON-LD, CDN hosts, RDAP, DNS TXT, Wayback, Common Crawl.",
        "use_when": "403/captcha/empty page — you still need public evidence.",
        "expected": "winning_method plus per-method findings.",
        "legal": "Passive public sources first. FlareSolverr / TLS impersonate run only after the operator risk gate.",
        "outputs": ["rss", "rdap", "wayback", "common_crawl"],
    },
    {
        "id": "swarm",
        "name": "Swarm Pheromones",
        "category": "probe",
        "summary": "Parallel micro-fetchers that remember sweet (useful) and poison (blocked) URL patterns in Redis or SQLite.",
        "use_when": "Authorized mapping of a site you operate, so later jobs skip dead ends.",
        "expected": "Per-worker notes and a pheromone log.",
        "legal": "Part of Active Probe. Live runs require authorized_target=true. Default is dry_run.",
        "outputs": ["pheromones", "worker results"],
    },
    {
        "id": "provocative_stock",
        "name": "Provocative Stock",
        "category": "probe",
        "summary": "On a shop you are allowed to test, submit an extreme cart quantity to read stock/validation errors the UI already returns.",
        "use_when": "You own the storefront and need availability signals that the product page hides.",
        "expected": "Request/response notes in dry_run; live only with authorization.",
        "legal": "Authorized testing only. Not for inventory theft against third parties. Prefer dry_run.",
        "outputs": ["validation_errors", "hints"],
    },
    {
        "id": "api_fuzz",
        "name": "API Fuzz",
        "category": "probe",
        "summary": "Shadow-map of same-origin paths the HTML already references, plus conservative path guesses.",
        "use_when": "Documenting your own app's public API surface.",
        "expected": "Candidate URLs and status codes. Not an exploit framework.",
        "legal": "No payload exploits, no auth bypass. Live requires authorized_target=true.",
        "outputs": ["candidates", "statuses"],
    },
    {
        "id": "temporal",
        "name": "Temporal Spoofing",
        "category": "probe",
        "summary": "Shift the browser clock for pages that gate content on Date() (countdown, embargo).",
        "use_when": "Authorized review of time-gated UX on a property you control.",
        "expected": "Before/after notes of visible content.",
        "legal": "Does not forge server-side sessions or TLS. Authorized hosts only.",
        "outputs": ["visible_delta"],
    },
    {
        "id": "ghost_cursor",
        "name": "Ghost Cursor",
        "category": "browser",
        "summary": "Bezier mouse paths, variable typing cadence, scroll pauses, and tiny viewport nudges during authorized Playwright sessions.",
        "use_when": "Vision scrape on a site that expects a real viewport — not to defeat bot management.",
        "expected": "More complete screenshots on ordinary pages.",
        "legal": "Human-like cadence. Canvas/WebGL profile overrides require the fingerprint_profiles risk option.",
        "outputs": ["screenshot"],
    },
    {
        "id": "privacy_layers",
        "name": "Privacy Layers",
        "category": "compliance",
        "summary": "ghost / standard / eu_shield / de_fortress / hunter — which methods are allowed and how PII is gated.",
        "use_when": "Research that must stay GDPR-aware or archive-only.",
        "expected": "Policy profile, allowed methods, GDPR mask counts.",
        "legal": "de_fortress and eu_shield tighten live collection and mask personal emails. Hunter is for ROW authorized research.",
        "outputs": ["layer", "allowed_methods"],
    },
    {
        "id": "corporate",
        "name": "Corporate intelligence",
        "category": "osint",
        "summary": "SEC EDGAR search, Companies House (API or search URL), OpenCorporates, GitHub public org metadata, careers-page signals, HTML tech-stack.",
        "use_when": "Company due diligence from public registries.",
        "expected": "Filings/search URLs, stack signatures, hiring page hits.",
        "legal": "Public APIs and search URLs. GitHub commit emails require the operator risk option.",
        "outputs": ["registries", "stack", "hiring"],
    },
    {
        "id": "people",
        "name": "People footprint",
        "category": "osint",
        "summary": "Wikipedia summary, GitHub public user, news search, LinkedIn search URL.",
        "use_when": "Public professional context for a named person already in the news or Wikipedia.",
        "expected": "Public snippets and search links — not a dossier of private emails.",
        "legal": "LinkedIn scrape and GitHub commit-email harvest stay off until the operator reads the notice, types the phrase, and enables those options. No stalking of private individuals.",
        "outputs": ["wikipedia", "github", "news", "linkedin_search"],
    },
    {
        "id": "byok",
        "name": "BYOK LLM hub",
        "category": "system",
        "summary": "Bring OpenRouter, OpenAI, Anthropic, Groq, NVIDIA, Hugging Face, or local Ollama. Light tasks go to fast/cheap models; dossiers use reasoning models.",
        "use_when": "You want Claude/DeepSeek/Llama without locking to NVIDIA/Groq.",
        "expected": "Health routing shows light vs reasoning provider:model chains.",
        "legal": "Keys stay on your host. Never paste secrets into Copilot chat.",
        "outputs": ["routing.light", "routing.reasoning"],
    },
    {
        "id": "risk_gate",
        "name": "Operator risk gate",
        "category": "compliance",
        "summary": "All high-risk options are off until you read the notice, confirm authorized use, type I ACCEPT THE RISK, and enable each switch.",
        "use_when": "You have a lawful basis and need FlareSolverr, TLS impersonation, fingerprint profiles, LinkedIn public fetch, or GitHub commit emails.",
        "expected": "Per-capability flags in Settings. APIs return 403 until the matching flag is on.",
        "legal": "You accept all liability. These options can violate site terms or GDPR if misused. Revoke anytime.",
        "outputs": ["acknowledged", "capabilities"],
    },
    {
        "id": "flaresolverr",
        "name": "FlareSolverr (BYO)",
        "category": "high-risk",
        "summary": "Forwards a URL to YOUR FlareSolverr instance. ArgosScout does not include a Cloudflare solver.",
        "use_when": "You run FlareSolverr locally and are allowed to fetch the target.",
        "expected": "HTML from the sidecar, or an error if the instance is down.",
        "legal": "Authorized hosts only. Enabling this does not grant extra rights against third-party sites.",
        "outputs": ["html_preview", "status"],
    },
    {
        "id": "tls_impersonate",
        "name": "TLS/JA3 impersonation",
        "category": "high-risk",
        "summary": "Optional curl_cffi Chrome TLS profile for GET. pip install curl_cffi.",
        "use_when": "Authorized testing against TLS fingerprint blocks.",
        "expected": "Status and HTML preview via impersonated client.",
        "legal": "Not a WAF exploit. Still SSRF-gated. Authorized use only.",
        "outputs": ["status", "impersonate"],
    },
    {
        "id": "fingerprint_profiles",
        "name": "Canvas / WebGL / Audio profiles",
        "category": "high-risk",
        "summary": "Playwright init script aligns platform, WebGL vendor/renderer, and AudioContext with the UA. No canvas noise.",
        "use_when": "Vision scrape on a property you may browse that inspects navigator/WebGL.",
        "expected": "Same screenshot pipeline with a coherent profile applied.",
        "legal": "Not a full anti-detect kit and not a challenge solver.",
        "outputs": ["init_script"],
    },
    {
        "id": "linkedin_fetch",
        "name": "LinkedIn public fetch",
        "category": "high-risk",
        "summary": "Unauthenticated GET of a LinkedIn URL. Login walls and 999 stop the attempt.",
        "use_when": "You have a lawful basis and only need public HTML/JSON-LD.",
        "expected": "Title and JSON-LD if the page is actually public; otherwise blocked.",
        "legal": "LinkedIn terms generally prohibit scraping. No session, no stealth login.",
        "outputs": ["title", "json_ld_preview"],
    },
    {
        "id": "github_commit_emails",
        "name": "GitHub commit author emails",
        "category": "high-risk",
        "summary": "Reads author.email from the public commits API for a repo you name.",
        "use_when": "Due diligence on a public repository you specify — not a person-hunt across GitHub.",
        "expected": "Deduped name/email pairs, including noreply.github.com addresses.",
        "legal": "Personal data. GDPR still applies. Do not build marketing or stalking lists.",
        "outputs": ["authors"],
    },
]


def get_playbook() -> dict[str, Any]:
    return {
        "title": "ArgosScout Feature Inspector",
        "stance": (
            "ArgosScout is a privacy-first research OS. Discovery collects unverified traces; "
            "Verification is an optional second pass and never a silent truth score. "
            "High-risk options (FlareSolverr sidecar, TLS impersonation, fingerprint profiles, "
            "LinkedIn public fetch, GitHub commit emails) stay off until the operator "
            "reads the notice, types the acceptance phrase, and enables each switch. "
            "When a live page refuses inspection, prefer the lawful fallback tree."
        ),
        "entries": ENTRIES,
        "ids": [e["id"] for e in ENTRIES],
    }


def get_entry(entry_id: str) -> Optional[dict[str, Any]]:
    for item in ENTRIES:
        if item["id"] == entry_id:
            return item
    return None
